-- Populate structured Ministry Profile content for the Communio demo dataset.
-- MIN004 is intentionally excluded because its approved profile is preserved.

with demo_profiles (
  ministry_id, ministry_code, patron_saint_name, feast_day, feast_month,
  motto, mission_statement, vision_statement, apostolic_focus,
  ministry_values, founding_story, history_summary
) as (
  values
    ('95addf95-0ee5-44df-b09a-bb7cb64b6d25'::uuid, 'MIN001', null, null, null,
      'Stewardship in Service',
      'To support sound governance, responsible stewardship, and coordinated service across the Province, enabling communities and ministries to fulfil their mission with continuity and accountability.',
      'A well-coordinated Province administration that strengthens communion, supports responsible leadership, and serves every community and ministry with clarity and care.',
      array['Governance Support','Province Coordination','Stewardship','Personnel Service','Administrative Continuity']::text[],
      array['Service','Integrity','Accountability','Communion','Stewardship']::text[],
      'Established in 1950, Provincial Administration developed in Bengaluru as the coordinating centre for the Province''s governance, finance, secretariat, personnel, and administrative responsibilities. Its role is to sustain the shared mission by offering dependable support to leadership, communities, and ministries.',
      'Over time, the administration has continued to strengthen coordination and institutional continuity as the Province''s communities and apostolates have grown. It remains a service ministry dedicated to prudent stewardship, clear communication, and responsible governance.'),

    ('a03222bc-511a-4c76-942c-0dc151bb30d0'::uuid, 'MIN002', 'St. Joseph', 19, 3,
      'Learning with Faith and Purpose',
      'To provide holistic, values-based education that cultivates academic excellence, character, creativity, physical development, and a commitment to serve others.',
      'Young people formed as capable, compassionate, and responsible citizens who use their knowledge and gifts for the common good.',
      array['School Education','Student Formation','Academic Excellence','Co-curricular Development','Service Learning']::text[],
      array['Faith','Excellence','Respect','Service','Integrity']::text[],
      'Established in 1995, St. Joseph School grew from the Province''s commitment to educating and forming young people in Bengaluru. Through classroom learning, sport, and co-curricular programmes, it seeks to unite academic development with enduring human and spiritual values.',
      'The school has continued to broaden opportunities for learning while preserving its values-based educational identity. Its academic and formative programmes remain centred on the balanced development of every student.'),

    ('9bd6f336-6701-4bf7-b999-e441946247c6'::uuid, 'MIN003', 'St. Antony of Padua', 13, 6,
      'Wisdom for Life and Service',
      'To offer rigorous higher education in arts, commerce, and science while nurturing ethical leadership, intellectual curiosity, social responsibility, and service.',
      'Graduates equipped with knowledge, character, and compassion to contribute thoughtfully to society and the wider human community.',
      array['Higher Education','Academic Formation','Research and Learning','Student Development','Social Responsibility']::text[],
      array['Wisdom','Excellence','Integrity','Service','Inclusion']::text[],
      'Established in 2002, St. Antony College developed in Bengaluru as the Province expanded its educational service into undergraduate and postgraduate formation. Its programmes bring academic study together with personal growth, ethical reflection, and preparation for responsible participation in society.',
      'The college has continued to develop its academic community and range of learning opportunities. Across its disciplines, it seeks to preserve a student-centred culture marked by intellectual seriousness, inclusion, and concern for the common good.'),

    ('10e1e115-aea5-46d2-89fc-329545addf7d'::uuid, 'MIN005', null, null, null,
      'Knowledge, Character, Service',
      'To accompany students from their earliest years through senior secondary education with strong academics, creative opportunity, disciplined growth, and values-based formation.',
      'A learning community where every student grows in knowledge, confidence, compassion, and readiness to serve society responsibly.',
      array['School Education','Holistic Development','Values Formation','Sports and Culture','Student Wellbeing']::text[],
      array['Faith','Discipline','Excellence','Compassion','Service']::text[],
      'Established in 1990, St. Antonia''s High School became part of the Province''s educational mission in Ranchi. It serves children and young people through academics, sport, cultural activities, and a formative environment that values both achievement and character.',
      'The school has continued to adapt its programmes to the changing educational needs of students and families. Its enduring purpose is to provide accessible, balanced formation within a caring and purposeful school community.'),

    ('32554b10-e542-4748-98e8-af570eb03185'::uuid, 'MIN006', 'St. Joseph', 19, 3,
      'Growing in Wisdom and Service',
      'To provide students in Rourkela with sound academic foundations, value education, creative activities, and attentive guidance for their personal development.',
      'Confident and compassionate young people prepared to learn continuously, live responsibly, and contribute positively to their communities.',
      array['School Education','Value Education','Student Formation','Creative Activities','Community Awareness']::text[],
      array['Faith','Respect','Diligence','Service','Responsibility']::text[],
      'Established in 2005, St. Joseph School in Rourkela developed as a local expression of the Province''s commitment to education. Its primary and secondary programmes seek to give students a dependable academic foundation alongside habits of responsibility, respect, and service.',
      'The school has continued to strengthen its learning environment and student activities while remaining attentive to local families. Its educational service is shaped by steady growth, pastoral concern, and the formation of the whole person.'),

    ('8a6e8a83-c954-426d-993e-5e1d83579ab0'::uuid, 'MIN007', 'Our Lady, Morning Star', null, null,
      'Rise, Learn, and Shine',
      'To form young people through excellent academics, cultural and sporting opportunities, pastoral care, and a school culture rooted in faith and service.',
      'A vibrant learning community where students discover their gifts and become hopeful, responsible, and compassionate contributors to society.',
      array['School Education','Student Formation','Pastoral Activities','Sports and Culture','Leadership Development']::text[],
      array['Faith','Hope','Excellence','Respect','Service']::text[],
      'Established in 1994, Morning Star School developed in Ranchi to serve young people through a broad programme of academic, cultural, sporting, and pastoral formation. Its name expresses a commitment to hope-filled education and patient accompaniment.',
      'Across the years, the school has continued to foster learning and student participation within a supportive community. Its programmes seek to respond to changing educational needs without losing sight of faith, character, and service.'),

    ('4e07214f-e7ab-4aa1-b0fe-b5c3f689095e'::uuid, 'MIN008', null, null, null,
      'Skills for Work and Dignity',
      'To provide practical technical education and vocational formation that strengthens competence, employability, confidence, and responsible participation in the workplace.',
      'Young people and adults empowered with useful skills, professional discipline, and opportunities to build dignified and sustainable livelihoods.',
      array['Technical Education','Vocational Skills','Employability','Practical Formation','Workplace Readiness']::text[],
      array['Dignity','Competence','Discipline','Service','Empowerment']::text[],
      'Established in 2001, Nazareth Technical Institute developed in Ranchi as a practical response to the need for vocational skill and employment-oriented education. It combines technical learning with personal discipline and preparation for responsible work.',
      'The institute has continued to align practical formation with evolving workplace needs. Its educational approach remains focused on usable competence, confidence, dignity of labour, and pathways toward sustainable livelihood.'),

    ('d06f85f1-b85b-488f-aae6-2d1dfc203973'::uuid, 'MIN009', 'St. Anne', 26, 7,
      'Formed in Wisdom and Grace',
      'To offer primary and secondary education that integrates sound learning, personal attention, moral formation, and respect for every student.',
      'A caring school community whose students grow in wisdom, confidence, responsibility, and generous service to others.',
      array['School Education','Values Formation','Student Care','Academic Growth','Community Service']::text[],
      array['Faith','Wisdom','Respect','Compassion','Service']::text[],
      'Established in 2000, St. Anne School began its educational service in Bengaluru with a commitment to values-based primary and secondary formation. It seeks to create a stable environment in which students can learn, mature, and discover their responsibilities toward others.',
      'The school has continued to strengthen its academic and formative work while retaining a caring institutional character. Its history reflects steady service to students and families through education attentive to both knowledge and values.'),

    ('d7cb2e79-44b5-4a25-a9c9-af112cb9dd27'::uuid, 'MIN010', 'St. Joseph', 19, 3,
      'Learn Deeply, Serve Generously',
      'To provide comprehensive school education that promotes academic achievement, creativity, character, collaboration, and a lifelong commitment to service.',
      'Students formed as thoughtful, capable, and compassionate persons ready to engage the world with confidence and integrity.',
      array['School Education','Academic Excellence','Co-curricular Learning','Character Formation','Student Leadership']::text[],
      array['Faith','Excellence','Integrity','Respect','Service']::text[],
      'Established in 2009, St. Joseph Academy in Kolkata joined the Province''s educational apostolate with a comprehensive programme from kindergarten through senior secondary level. It brings academic formation together with co-curricular learning and the development of character.',
      'The academy has continued to develop its learning culture and opportunities for student participation. Its institutional journey remains guided by academic care, personal responsibility, and education directed toward service and the common good.'),

    ('de1322c1-2867-4ab6-acc4-032f8cfc8e53'::uuid, 'MIN011', null, null, null,
      'Called, Accompanied, Sent',
      'To awaken vocation awareness, accompany young people in discernment, and provide prayerful opportunities to explore a call to religious and missionary life.',
      'Young people freely discerning God''s call with maturity, faith, self-knowledge, and generous openness to a life of service.',
      array['Vocation Awareness','Discernment','Personal Accompaniment','Youth Engagement','Prayer and Outreach']::text[],
      array['Faith','Freedom','Discernment','Hospitality','Mission']::text[],
      'Established in 1992, the Vocation Office developed in Bengaluru to coordinate the Province''s vocation awareness and accompaniment. Through outreach, discernment programmes, and personal guidance, it helps young people reflect prayerfully on their gifts and possible call to religious life.',
      'The office has continued to adapt its outreach to new generations while preserving the personal and prayerful nature of vocation accompaniment. Its work connects youth engagement with careful discernment and the wider formation mission of the Province.'),

    ('f78041f9-6938-42bf-93fe-bf1e19aa4ead'::uuid, 'MIN012', null, null, null,
      'Come, Discern, and Grow',
      'To introduce candidates to prayer, community life, human development, and the mission of the congregation while helping each person discern a vocation with freedom and maturity.',
      'Candidates grounded in self-knowledge, faith, healthy relationships, and a clearer readiness to continue—or freely conclude—the journey of religious formation.',
      array['Vocation Discernment','Human Formation','Introduction to Prayer','Community Life','Mission Awareness']::text[],
      array['Freedom','Openness','Prayer','Maturity','Community']::text[],
      'Established in 1998, the Aspirancy and Postulancy Program developed in Bengaluru as the Province''s introductory stage of formation. It offers candidates a gradual experience of prayer, community, accompaniment, study, and service while supporting an honest discernment of religious life.',
      'The program has continued to refine its accompaniment of candidates from varied backgrounds. Its focus remains introductory and discerning: building human foundations, familiarity with the congregation, and sufficient freedom for the next stage of formation.'),

    ('c348e938-274f-4a0a-a213-5be0fb0f9aac'::uuid, 'MIN013', null, null, null,
      'Rooted in Christ, Formed for Mission',
      'To guide novices through intensive spiritual and religious formation in prayer, the evangelical counsels, community life, congregational identity, and discernment for profession.',
      'Novices deeply rooted in Christ, growing in interior freedom and communal responsibility, and prepared to embrace religious commitment with maturity.',
      array['Spiritual Formation','Religious Life','Prayer and Discernment','Community Formation','Congregational Charism']::text[],
      array['Prayer','Simplicity','Obedience','Communion','Discernment']::text[],
      'Established in 1955, the Novitiate Program in Ranchi became the Province''s focused setting for canonical and spiritual preparation in religious life. It provides novices with sustained prayer, instruction, accompaniment, community experience, and discernment before profession.',
      'Through changing times, the novitiate has retained its distinctive purpose as an intensive school of prayer and religious living. Its formation continues to integrate personal growth, congregational identity, the evangelical counsels, and readiness for committed mission.'),

    ('3d4a3820-592f-43a9-b98a-00feedcd90b9'::uuid, 'MIN014', null, null, null,
      'Study, Community, Mission',
      'To accompany professed members through academic and theological study, continued human and spiritual growth, community life, and supervised preparation for ministry.',
      'Religious who integrate faith, learning, fraternity, and pastoral competence in mature and generous service to the Church and society.',
      array['Academic Formation','Theological Study','Spiritual Growth','Community Life','Ministerial Preparation']::text[],
      array['Faith','Study','Fraternity','Discipline','Mission']::text[],
      'Established in 1960, the Scholasticate Program developed in Pune to accompany professed members during advanced studies and preparation for ministry. Its formative environment brings academic work into dialogue with prayer, community responsibility, personal maturation, and pastoral experience.',
      'The scholasticate has continued to respond to the academic and ministerial needs of formation while preserving an integrated approach. Its institutional memory reflects the patient preparation of members for informed, collaborative, and spiritually grounded service.'),

    ('b881baf7-4a3a-4251-87d2-e840375b79b2'::uuid, 'MIN015', null, null, null,
      'Education Rooted in Community',
      'To provide children and young people in Budakata with accessible, values-based education, attentive formation, and opportunities for participation and growth.',
      'A locally rooted school community where students gain knowledge, confidence, character, and hope for their future.',
      array['School Education','Community Outreach','Student Formation','Academic Foundations','Co-curricular Activities']::text[],
      array['Dignity','Respect','Diligence','Compassion','Service']::text[],
      'Established in 2012, Budakata School developed within the Province''s mission presence in Sundargarh as a commitment to local education and community engagement. Its primary and secondary programmes seek to support students through learning, activities, and values-based formation.',
      'The school has continued to grow alongside the community it serves. Its educational work remains attentive to local realities, student participation, strong academic foundations, and the wider wellbeing of children and families.'),

    ('99b97d51-8fcf-4012-a85a-decdd9a3e260'::uuid, 'MIN016', 'St. Alphonsa', 28, 7,
      'Come Away and Be Renewed',
      'To offer retreats, recollections, spiritual direction, and formation programmes that create space for prayer, discernment, healing, and renewed relationship with God.',
      'A welcoming centre where people encounter peace, reconciliation, spiritual renewal, and strength for faithful daily living.',
      array['Retreats','Prayer','Spiritual Direction','Reconciliation','Faith Formation']::text[],
      array['Hospitality','Prayer','Compassion','Silence','Renewal']::text[],
      'Established in 2010, St. Alphonsa Retreat Centre developed in Bengaluru as a dedicated place for retreats, recollections, spiritual accompaniment, and faith formation. Its ministry provides individuals and groups with a prayerful setting away from ordinary demands.',
      'The centre has continued to serve varied spiritual needs through guided programmes and personal accompaniment. Its history is marked by a consistent emphasis on hospitality, interior renewal, reconciliation, and the integration of prayer with daily life.'),

    ('b3541e98-255e-4be0-8167-0a6e3d6b04ec'::uuid, 'MIN017', 'St. Antony of Padua', 13, 6,
      'Dignity through Compassionate Action',
      'To accompany vulnerable communities through education, family support, livelihood initiatives, and participatory development that strengthens dignity and self-reliance.',
      'Communities empowered to shape just, resilient, and hopeful futures through opportunity, solidarity, and shared responsibility.',
      array['Community Development','Livelihood Support','Family Empowerment','Education','Social Inclusion']::text[],
      array['Dignity','Justice','Compassion','Solidarity','Empowerment']::text[],
      'Established in 2004, St. Antony Social Service Centre developed in Ranchi as an organized expression of the Province''s commitment to vulnerable families and communities. Its programmes connect education, livelihood, family support, and community participation.',
      'The centre has continued to shape its services around evolving social and economic needs. Its institutional approach emphasizes respectful partnership, practical empowerment, inclusion, and development that strengthens the agency of the people it serves.'),

    ('05ac8667-9bee-4e3b-8bac-4b18e16d0217'::uuid, 'MIN018', 'St. Joseph', 19, 3,
      'Healing with Dignity and Care',
      'To provide accessible primary health care, outpatient treatment, preventive education, and community health outreach with compassion and respect for every person.',
      'Healthier communities supported by dependable care, informed prevention, human dignity, and special concern for those with limited access to services.',
      array['Primary Health Care','Preventive Care','Community Health','Outpatient Service','Health Education']::text[],
      array['Compassion','Dignity','Service','Competence','Accessibility']::text[],
      'Established in 2014, St. Joseph Health Centre developed in Budakata to provide primary treatment, preventive care, and health outreach within the surrounding community. Its service seeks to combine professional attention with compassion and respect for human dignity.',
      'The centre has continued to respond to everyday health needs through outpatient care, community awareness, and periodic outreach. Its developing history reflects a practical healing ministry centred on accessibility, prevention, and attentive service.'),

    ('1228afac-64d4-48b6-bfdb-d2e3c3569c2e'::uuid, 'MIN019', 'Our Lady of Peace', null, null,
      'Peace through Faith and Communion',
      'To gather the parish community in worship, sacramental life, catechesis, family accompaniment, youth engagement, and compassionate outreach.',
      'A welcoming communion of faith where people encounter Christ, grow together, and become instruments of peace and service in society.',
      array['Liturgy','Pastoral Care','Catechesis','Family Ministry','Community Outreach']::text[],
      array['Faith','Peace','Communion','Compassion','Mission']::text[],
      'Established in 1999, Our Lady of Peace Parish developed in Bengaluru as a local community of worship, pastoral care, catechesis, and outreach. Its dedication expresses the hope that parish life will form people in reconciliation, communion, and service.',
      'The parish has continued to accompany families and individuals through sacramental life, faith formation, and pastoral presence. Its institutional journey remains rooted in shared worship and an outward-looking commitment to peace and compassionate service.'),

    ('d27ce6a4-bf70-4470-94e6-0332e090cabd'::uuid, 'MIN020', 'Blessed Virgin Mary', null, null,
      'Gathered in Faith, Sent in Love',
      'To serve the parish community through liturgy, the sacraments, catechesis, pastoral accompaniment, and outreach attentive to local needs.',
      'A prayerful and missionary parish in which families and individuals grow in faith, communion, and generous care for their neighbours.',
      array['Liturgy','Sacramental Ministry','Catechesis','Pastoral Care','Evangelization']::text[],
      array['Faith','Communion','Hospitality','Service','Mission']::text[],
      'Established in 2002, St. Mary''s Parish developed in Rourkela as a community centred on worship, sacramental ministry, catechesis, and pastoral outreach. Its life seeks to support families and individuals in faithful Christian discipleship.',
      'Over time, the parish has continued to deepen its pastoral presence and respond to the spiritual needs of the local community. Its history is carried forward through shared prayer, faith formation, compassionate accompaniment, and missionary service.'),

    ('78d5d361-4761-429f-9952-73b08a1253e2'::uuid, 'MIN021', null, null, null,
      'Young in Faith, Ready to Serve',
      'To accompany young people through faith formation, leadership development, retreats, service, vocation awareness, and opportunities for meaningful community participation.',
      'Young people confident in faith, generous in service, capable of leadership, and attentive to their vocation in Church and society.',
      array['Youth Accompaniment','Faith Formation','Leadership','Service','Vocation Awareness']::text[],
      array['Faith','Joy','Leadership','Solidarity','Mission']::text[],
      'Established in 2016, St. Antonia''s Youth Ministry developed in Bengaluru to coordinate the Province''s accompaniment of young people. Retreats, camps, formation, leadership opportunities, and outreach provide spaces for faith, friendship, responsibility, and discernment.',
      'The ministry has continued to adapt its programmes to the experiences and questions of young people. Its institutional direction remains participatory and hopeful, encouraging youth to lead, serve, deepen their faith, and reflect on their vocation.'),

    ('bc2b9cde-62e7-4c4e-b6ff-e0331385856b'::uuid, 'MIN022', 'St. Antony of Padua', 13, 6,
      'A Home for Learning and Growth',
      'To provide students with a safe and supportive residential community that integrates study, daily responsibility, recreation, pastoral care, and character formation.',
      'Residents growing in confidence, discipline, friendship, and educational commitment within a caring community away from home.',
      array['Student Care','Residential Community','Study Support','Character Formation','Pastoral Accompaniment']::text[],
      array['Hospitality','Respect','Discipline','Community','Responsibility']::text[],
      'Established in 2008, St. Antony Hostel developed in Bengaluru to provide students with a stable residential setting alongside their education. It combines accommodation and study support with recreation, shared responsibility, pastoral care, and community life.',
      'The hostel has continued to serve students from varied backgrounds by fostering a safe, orderly, and welcoming environment. Its residential tradition emphasizes mutual respect, disciplined study, healthy relationships, and growth in personal responsibility.'),

    ('c6a1de47-049d-4d25-ba27-7828a287a02e'::uuid, 'MIN023', 'St. Joseph', 19, 3,
      'Practical Skills, Hopeful Futures',
      'To equip young people and adults with vocational, technical, and employability skills through practical formation connected to real opportunities for work and livelihood.',
      'Learners empowered by competence, confidence, and professional discipline to pursue dignified employment and contribute to their communities.',
      array['Vocational Training','Technical Skills','Employability','Certificate Programmes','Livelihood Empowerment']::text[],
      array['Dignity','Competence','Discipline','Opportunity','Service']::text[],
      'Established in 2011, St. Joseph Skill Centre developed in Rourkela to expand access to practical vocational and technical formation. Its programmes help learners build useful competence, workplace habits, confidence, and pathways toward employment.',
      'The centre has continued to shape its training around changing skill and employment needs. Its institutional focus remains practical and empowering, joining technical instruction with discipline, personal development, and respect for the dignity of work.'),

    ('566df733-f9f5-4d6c-8501-0b85d5c49ba8'::uuid, 'MIN024', null, null, null,
      'Connecting the Province in Mission',
      'To support clear, responsible, and creative communication across the Province through publications, digital media, information sharing, and coordinated outreach.',
      'A connected Province whose communities and ministries communicate their life and mission with clarity, trust, accessibility, and evangelical purpose.',
      array['Province Communication','Digital Ministry','Publications','Information Sharing','Media Outreach']::text[],
      array['Truth','Clarity','Creativity','Communion','Responsibility']::text[],
      'Established in 2017, the Province Communications Office developed in Bengaluru to coordinate publications, web communication, media, and information sharing. It serves the Province by helping communities and ministries remain connected and communicate their mission responsibly.',
      'The office has continued to respond to the growing importance of digital communication and timely information. Its institutional role brings together editorial care, accessible technology, creative outreach, and service to the shared identity of the Province.')
)
update public.ministries as ministry
set patron_saint_name = coalesce(ministry.patron_saint_name, profile.patron_saint_name),
    feast_day = coalesce(ministry.feast_day, profile.feast_day),
    feast_month = coalesce(ministry.feast_month, profile.feast_month),
    motto = coalesce(ministry.motto, profile.motto),
    mission_statement = coalesce(ministry.mission_statement, profile.mission_statement),
    vision_statement = coalesce(ministry.vision_statement, profile.vision_statement),
    apostolic_focus = coalesce(ministry.apostolic_focus, profile.apostolic_focus),
    ministry_values = coalesce(ministry.ministry_values, profile.ministry_values),
    founding_story = coalesce(ministry.founding_story, profile.founding_story),
    history_summary = coalesce(ministry.history_summary, profile.history_summary)
from demo_profiles as profile
join public.v_demo_ministry_operational as operational
  on operational.ministry_code = profile.ministry_code
where ministry.id = operational.ministry_id
  and operational.ministry_id = profile.ministry_id;
